spring:
  favicon:
    enabled: false
  application:
    name: converter
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8081
  servlet:
    context-path: /cv

api.base.url: http://api.exchangeratesapi.io/latest?access_key=15a1a801648783aac5cffff45858a66e
